### ISSUE TITLE
[Proposal] generate types directly from csv files

### ISSUE THREAD

**Issue by dkuku** [arathunku/ext_fit#4]
I saw that the rust library generates the code from the csv directly. I see you have a script for that currently. 
You can do this with a macro - this way when there is a new csv file with mappings you only need to replace it in the repo and mark it with `@external_resource`.
This is quite popular pattern [elixir unicode](https://github.com/elixir-lang/elixir/tree/main/lib/elixir/unicode),  [ex_cldr](https://github.com/elixir-cldr/cldr/blob/f6112a89f31f3659c22f0d8e595e345b8a6af451/mix.exs#L74), gettext

**Comment by arathunku** [comment]
This is a deliberate decision. I strongly prefer [formatted and committed into repo Elixir](https://github.com/arathunku/ext_fit/blob/6b8346f4a74c6d0601e389424468abbce4b3a092/lib/ext_fit/profile/types.ex) code that uses macros instead of CSV. I also avoid shipping CSV as a dependency in this case. [CSV definitions are still part of the repo](https://github.com/arathunku/ext_fit/blob/main/sdks/profile-21.126.00/Profile-Types.csv), just not required for end user.
